<a href="https://colab.research.google.com/github/Nniichha/229352-StatisticalLearning/blob/main/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [1]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [20]:
x = torch.tensor([5])
x.shape


torch.Size([1])

### Convert a tensor to scalar

In [23]:
x = torch.tensor([5])
y = x.item()

### Creating 2D tensor

In [25]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x)
print(x.shape)


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


## Tensor and Numpy

### Convert from tensor to numpy array

In [27]:
x = torch.tensor([1, 2, 3])
np_x = x.numpy()
print(np_x)

[1 2 3]


### Convert from numpy array to tensor

In [28]:
np_x = np.array([1, 2, 3])
x = torch.from_numpy(np_x)
print(x)

tensor([1, 2, 3])


## PyTorch and GPU

check if GPU is available

In [7]:
torch.cuda.is_available()

True

## Basic operations

In [29]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.add(a, b)
torch.sub(a, b)
torch.mul(a, b)
torch.div(a, b)

tensor([0.2500, 0.4000, 0.5000])

### Matrix multiplication

In [30]:
x = torch.tensor([[1, 2],
                  [3, 4]])
y = torch.tensor([[5, 6],
                  [7, 8]])

x @ y


tensor([[19, 22],
        [43, 50]])

In [32]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(x @ y)


tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])
tensor([[19, 22],
        [43, 50]])


### Matrix transpose

In [33]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

x_t = x.T
print(x_t)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


## Creating a specific type of tensor

In [34]:

# Integer tensor
x_int = torch.tensor([1, 2, 3], dtype=torch.int32)

# Float tensor
x_float = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

# Zero tensor
x_zeros = torch.zeros((2, 3))

# Ones tensor
x_ones = torch.ones((2, 3))

# Identity matrix
x_eye = torch.eye(3)

# Random tensor
x_rand = torch.rand((2, 3))

# Random integer tensor
x_randint = torch.randint(0, 10, (2, 3))

print(x_int)
print(x_float)
print(x_zeros)
print(x_ones)
print(x_eye)
print(x_rand)
print(x_randint)


tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0.7789, 0.2241, 0.3058],
        [0.3211, 0.4100, 0.9138]])
tensor([[7, 1, 3],
        [2, 3, 5]])


## Tensor's shape

### Checking the shape of a tensor

In [36]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])


x.shape

torch.Size([2, 3])

### Changing the shape of a tensor

In [44]:
#เปลี่ยน shape ด้วย reshape()
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])


In [45]:

y = x.reshape(3, 2)
y


tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [46]:
y = x.view(3, 2)
y


tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [47]:
y = x.reshape(-1, 2)


In [48]:
#เพิ่มมิติ
y = x.unsqueeze(0)


In [49]:
#ลดมิติ
z = torch.tensor([[1, 2, 3]])
z.squeeze()


tensor([1, 2, 3])

In [50]:
print(x.shape)
print(y.shape)


torch.Size([2, 3])
torch.Size([1, 2, 3])


In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [51]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Concatenate (ต่อกันในมิติเดิม)
cat_tensor = torch.cat((a, b), dim=0)

# Stack (เพิ่มมิติใหม่)
stack_tensor = torch.stack((a, b), dim=0)

print(cat_tensor)
print(stack_tensor)

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [53]:
# concatenate
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# concatenate
c = torch.cat((a, b), dim=0)

print(c)
x = torch.tensor([[1, 2],
                  [3, 4]])
y = torch.tensor([[5, 6],
                  [7, 8]])

# ต่อแถว (dim=0)
torch.cat((x, y), dim=0)

# ต่อคอลัมน์ (dim=1)
torch.cat((x, y), dim=1)


tensor([1, 2, 3, 4, 5, 6])


tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

### Squeezing a tensor (removing an extra dimension)

In [54]:
x = torch.tensor([[1, 2, 3]])

y = x.squeeze()

print(y)
print(y.shape)


tensor([1, 2, 3])
torch.Size([3])


### Unsqueezing a tensor (adding an extra dimension)

In [56]:
#H.shape = (6, )
H = torch.tensor([1, 2, 3, 4, 5, 6])


H_unsq = H.unsqueeze(0)

print(H_unsq)
print(H_unsq.shape)

tensor([[1, 2, 3, 4, 5, 6]])
torch.Size([1, 6])


## Indexing

In [57]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [58]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [59]:
torch.manual_seed(0)

n = 200
p = 7

X = torch.randn(n, p)
b = torch.randn(p + 1, 1)
e = torch.randn(n, 1)

ones = torch.ones(n, 1)

X = torch.cat((ones, X), dim=1)

y = X @ b + e

XtX = X.T @ X
XtX_inv = torch.inverse(XtX)
b_hat = XtX_inv @ (X.T @ y)

y_hat = X @ b_hat

y_np = y.detach().cpu().numpy()
yhat_np = y_hat.detach().cpu().numpy()

mse = (1/n) * np.sum((y_np - yhat_np) ** 2)
print("Shapes:", X.shape, b.shape, y.shape, b_hat.shape, y_hat.shape)
print("MSE =", mse)


Shapes: torch.Size([200, 8]) torch.Size([8, 1]) torch.Size([200, 1]) torch.Size([8, 1]) torch.Size([200, 1])
MSE = 0.9451753
